server:
  port: 8080

##freemarker
#  spring.freemarker.template-loader-path=classpath:/templates/
#  spring.freemarker.prefix=/freemarker/
#  spring.freemarker.suffix=.ftl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EXAMPLE
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: none
    showSql: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher