server:
  port: 8080

##freemarker
#  spring.freemarker.template-loader-path=classpath:/templates/
#  spring.freemarker.prefix=/freemarker/
#  spring.freemarker.suffix=.ftl

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: none
    showSql: true
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
  mvc:
    pathmatch:
      matching-strategy: ant_path-matcher